# Generated by Django 3.2.3 on 2021-11-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inf', '0008_remove_stocks_tabla_stock_centro'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks_tabla',
            name='duracion_stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
