# Generated by Django 3.2.3 on 2021-11-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inf', '0009_stocks_tabla_duracion_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks_tabla',
            name='duracion_stock',
            field=models.IntegerField(default=0),
        ),
    ]
