# Generated by Django 3.2.3 on 2021-11-17 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('inf', '0010_alter_stocks_tabla_duracion_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks_datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_umaad', models.IntegerField(default=0, null=True)),
                ('stock_nck', models.IntegerField(default=0, null=True)),
                ('ingreso_umaad', models.IntegerField(default=0, null=True)),
                ('egreso_umaad', models.IntegerField(default=0, null=True)),
                ('ingreso_nck', models.IntegerField(default=0, null=True)),
                ('egreso_nck', models.IntegerField(default=0, null=True)),
                ('duracion_stock', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.productos')),
            ],
        ),
    ]
