# Generated by Django 3.2.3 on 2021-11-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf', '0012_remove_stocks_tabla_duracion_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks_tabla',
            old_name='ingreso_umaad',
            new_name='duracion_umaad',
        ),
    ]
