# Generated by Django 3.2.3 on 2021-11-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf', '0013_rename_ingreso_umaad_stocks_tabla_duracion_umaad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stocks_datos',
        ),
    ]
