# Generated by Django 3.2.3 on 2021-11-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf', '0014_delete_stocks_datos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks_tabla',
            old_name='duracion_umaad',
            new_name='ingreso_umaad',
        ),
    ]
