# Generated by Django 3.2.3 on 2021-11-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('inf', '0015_rename_duracion_umaad_stocks_tabla_ingreso_umaad'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks_tabla',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.centro'),
        ),
    ]
