# Generated by Django 3.2.3 on 2021-11-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitos',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
