# Generated by Django 3.2.3 on 2021-11-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_remitos_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='renglones',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
