# Generated by Django 3.2.3 on 2021-11-23 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_renglones_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remitos',
            name='fecha_remito',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
