# Generated by Django 3.2.3 on 2021-11-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_alter_renglones_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitos',
            name='comentario',
            field=models.CharField(default='', max_length=100),
        ),
    ]
