# Generated by Django 3.2.3 on 2021-11-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_remitos_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remitos',
            name='comentario',
        ),
    ]
