# Generated by Django 3.2.3 on 2021-11-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks_tabla2',
            name='duracion_nck',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stocks_tabla2',
            name='duracion_umaad',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
