# Generated by Django 3.2.3 on 2021-11-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20211123_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumos_mensuales2',
            name='anio',
            field=models.IntegerField(default=2021, null=True),
        ),
        migrations.AddField(
            model_name='consumos_mensuales2',
            name='mes',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
