# Generated by Django 3.2.3 on 2021-11-24 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20211123_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumos_mensuales2',
            name='fecha',
        ),
    ]
