# Generated by Django 3.2.3 on 2021-11-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('info', '0005_remove_consumos_mensuales2_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='IES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.IntegerField(default=0, null=True)),
                ('egreso', models.IntegerField(default=0, null=True)),
                ('stock', models.IntegerField(default=0, null=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.centro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.productos')),
            ],
        ),
    ]
