# Generated by Django 3.2.3 on 2021-11-25 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('info', '0006_ies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumos_mensual_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('costo', models.FloatField(default=0, null=True)),
                ('promedio', models.FloatField(default=0, null=True)),
                ('costopromedio', models.FloatField(default=0, null=True)),
                ('anio', models.IntegerField(default=2021, null=True)),
                ('mes', models.IntegerField(default=1, null=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.proveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.productos')),
            ],
        ),
    ]
