# Generated by Django 3.2.3 on 2021-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_consumos_mensual_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks_tabla2',
            name='duracion_nck',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stocks_tabla2',
            name='duracion_umaad',
            field=models.FloatField(default=0, null=True),
        ),
    ]
