# Generated by Django 3.2.3 on 2021-11-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('idcentro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_centro', models.CharField(max_length=25)),
                ('area', models.CharField(blank=True, max_length=25)),
                ('direccion', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproductos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('categoria', models.CharField(blank=True, choices=[('m', 'Medicamento'), ('d', 'Descartables'), ('s', 'Soluciones'), ('al', 'Alimentos'), ('o', 'Otros')], max_length=20)),
                ('subcategoria', models.CharField(blank=True, max_length=15)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, max_length=30)),
                ('detalle', models.CharField(blank=True, max_length=100)),
                ('stock_critico', models.FloatField(blank=True, null=True)),
                ('stock_disponible', models.IntegerField(blank=True, default=0, null=True)),
                ('egreso', models.IntegerField(blank=True, default=0, null=True)),
                ('ingreso', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=25)),
                ('otros_datos', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
